lista_de_pessoas = [
    {
        "nome": "Cristiano Ronaldo",
        "seguidores_instagram": 631000000,
        "descricao_rapida": "Jogador de futebol português",
        "pais_origem": "Portugal",
    },
    {
        "nome": "Lionel Messi",
        "seguidores_instagram": 503000000,
        "descricao_rapida": "Jogador de futebol argentino",
        "pais_origem": "Argentina",
    },
    {
        "nome": "Selena Gomez",
        "seguidores_instagram": 429000000,
        "descricao_rapida": "Cantora e atriz americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Kylie Jenner",
        "seguidores_instagram": 399000000,
        "descricao_rapida": "Empresária e personalidade de mídia",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": 'Dwayne "The Rock" Johnson',
        "seguidores_instagram": 397000000,
        "descricao_rapida": "Ator e ex-lutador profissional",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Ariana Grande",
        "seguidores_instagram": 380000000,
        "descricao_rapida": "Cantora e atriz americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Kim Kardashian",
        "seguidores_instagram": 364000000,
        "descricao_rapida": "Empresária e personalidade de mídia",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Beyoncé",
        "seguidores_instagram": 319000000,
        "descricao_rapida": "Cantora, compositora e atriz",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Khloé Kardashian",
        "seguidores_instagram": 311000000,
        "descricao_rapida": "Personalidade de mídia e socialite",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Justin Bieber",
        "seguidores_instagram": 293000000,
        "descricao_rapida": "Cantor e compositor canadense",
        "pais_origem": "Canadá",
    },
    {
        "nome": "Kendall Jenner",
        "seguidores_instagram": 294000000,
        "descricao_rapida": "Modelo e personalidade de mídia",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Taylor Swift",
        "seguidores_instagram": 283000000,
        "descricao_rapida": "Cantora e compositora americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Virat Kohli",
        "seguidores_instagram": 266000000,
        "descricao_rapida": "Jogador de críquete indiano",
        "pais_origem": "Índia",
    },
    {
        "nome": "Jennifer Lopez",
        "seguidores_instagram": 253000000,
        "descricao_rapida": "Cantora, atriz e dançarina",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Neymar Jr.",
        "seguidores_instagram": 220000000,
        "descricao_rapida": "Jogador de futebol brasileiro",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Nicki Minaj",
        "seguidores_instagram": 229000000,
        "descricao_rapida": "Rapper, cantora e compositora",
        "pais_origem": "Trinidad e Tobago",
    },
    {
        "nome": "Kourtney Kardashian",
        "seguidores_instagram": 224000000,
        "descricao_rapida": "Personalidade de mídia e socialite",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Miley Cyrus",
        "seguidores_instagram": 216000000,
        "descricao_rapida": "Cantora, compositora e atriz",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Katy Perry",
        "seguidores_instagram": 207000000,
        "descricao_rapida": "Cantora e compositora americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Zendaya",
        "seguidores_instagram": 185000000,
        "descricao_rapida": "Atriz e cantora americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Kevin Hart",
        "seguidores_instagram": 179000000,
        "descricao_rapida": "Comediante e ator americano",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Cardi B",
        "seguidores_instagram": 169000000,
        "descricao_rapida": "Rapper e compositora americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "LeBron James",
        "seguidores_instagram": 159000000,
        "descricao_rapida": "Jogador de basquete profissional",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Demi Lovato",
        "seguidores_instagram": 157000000,
        "descricao_rapida": "Cantora, compositora e atriz",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Rihanna",
        "seguidores_instagram": 152000000,
        "descricao_rapida": "Cantora, empresária e atriz",
        "pais_origem": "Barbados",
    },
    {
        "nome": "Chris Brown",
        "seguidores_instagram": 145000000,
        "descricao_rapida": "Cantor, compositor e dançarino",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Drake",
        "seguidores_instagram": 143000000,
        "descricao_rapida": "Rapper, cantor e ator",
        "pais_origem": "Canadá",
    },
    {
        "nome": "Ellen DeGeneres",
        "seguidores_instagram": 139000000,
        "descricao_rapida": "Comediante e apresentadora de TV",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Kylian Mbappé",
        "seguidores_instagram": 112000000,
        "descricao_rapida": "Jogador de futebol francês",
        "pais_origem": "França",
    },
    {
        "nome": "Billie Eilish",
        "seguidores_instagram": 110000000,
        "descricao_rapida": "Cantora e compositora americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Gal Gadot",
        "seguidores_instagram": 109000000,
        "descricao_rapida": "Atriz e modelo israelense",
        "pais_origem": "Israel",
    },
    {
        "nome": "Vin Diesel",
        "seguidores_instagram": 101000000,
        "descricao_rapida": "Ator e produtor americano",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Lisa (BLACKPINK)",
        "seguidores_instagram": 100000000,
        "descricao_rapida": "Rapper e dançarina tailandesa",
        "pais_origem": "Tailândia",
    },
    {
        "nome": "Shakira",
        "seguidores_instagram": 90400000,
        "descricao_rapida": "Cantora e compositora colombiana",
        "pais_origem": "Colômbia",
    },
    {
        "nome": "David Beckham",
        "seguidores_instagram": 87300000,
        "descricao_rapida": "Ex-jogador de futebol inglês",
        "pais_origem": "Reino Unido",
    },
    {
        "nome": "Dua Lipa",
        "seguidores_instagram": 88700000,
        "descricao_rapida": "Cantora e compositora britânica",
        "pais_origem": "Reino Unido",
    },
    {
        "nome": "Priyanka Chopra",
        "seguidores_instagram": 90800000,
        "descricao_rapida": "Atriz e produtora indiana",
        "pais_origem": "Índia",
    },
    {
        "nome": "Shraddha Kapoor",
        "seguidores_instagram": 88600000,
        "descricao_rapida": "Atriz e cantora indiana",
        "pais_origem": "Índia",
    },
    {
        "nome": "Jennie (BLACKPINK)",
        "seguidores_instagram": 84700000,
        "descricao_rapida": "Cantora e rapper sul-coreana",
        "pais_origem": "Coreia do Sul",
    },
    {
        "nome": "Snoop Dogg",
        "seguidores_instagram": 85500000,
        "descricao_rapida": "Rapper e personalidade de mídia",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Jisoo (BLACKPINK)",
        "seguidores_instagram": 78900000,
        "descricao_rapida": "Cantora e atriz sul-coreana",
        "pais_origem": "Coreia do Sul",
    },
    {
        "nome": "Rosé (BLACKPINK)",
        "seguidores_instagram": 78000000,
        "descricao_rapida": "Cantora e dançarina neozelandesa",
        "pais_origem": "Nova Zelândia",
    },
    {
        "nome": "Gigi Hadid",
        "seguidores_instagram": 79000000,
        "descricao_rapida": "Modelo americana",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Ronaldinho",
        "seguidores_instagram": 75900000,
        "descricao_rapida": "Ex-jogador de futebol brasileiro",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Anitta",
        "seguidores_instagram": 65000000,
        "descricao_rapida": "Cantora e compositora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Maluma",
        "seguidores_instagram": 64100000,
        "descricao_rapida": "Cantor e compositor colombiano",
        "pais_origem": "Colômbia",
    },
    {
        "nome": "Karim Benzema",
        "seguidores_instagram": 76500000,
        "descricao_rapida": "Jogador de futebol francês",
        "pais_origem": "França",
    },
    {
        "nome": "Whindersson Nunes",
        "seguidores_instagram": 59500000,
        "descricao_rapida": "Comediante e youtuber brasileiro",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Sergio Ramos",
        "seguidores_instagram": 63200000,
        "descricao_rapida": "Jogador de futebol espanhol",
        "pais_origem": "Espanha",
    },
    {
        "nome": "Paulo Dybala",
        "seguidores_instagram": 57900000,
        "descricao_rapida": "Jogador de futebol argentino",
        "pais_origem": "Argentina",
    },
    {
        "nome": "Zlatan Ibrahimović",
        "seguidores_instagram": 64400000,
        "descricao_rapida": "Ex-jogador de futebol sueco",
        "pais_origem": "Suécia",
    },
    {
        "nome": "Mohamed Salah",
        "seguidores_instagram": 63600000,
        "descricao_rapida": "Jogador de futebol egípcio",
        "pais_origem": "Egito",
    },
    {
        "nome": "Gareth Bale",
        "seguidores_instagram": 53200000,
        "descricao_rapida": "Ex-jogador de futebol galês",
        "pais_origem": "País de Gales",
    },
    {
        "nome": "Marcelo Vieira",
        "seguidores_instagram": 67200000,
        "descricao_rapida": "Jogador de futebol brasileiro",
        "pais_origem": "Brasil",
    },
    {
        "nome": "James Rodríguez",
        "seguidores_instagram": 52300000,
        "descricao_rapida": "Jogador de futebol colombiano",
        "pais_origem": "Colômbia",
    },
    {
        "nome": "Paul Pogba",
        "seguidores_instagram": 61600000,
        "descricao_rapida": "Jogador de futebol francês",
        "pais_origem": "França",
    },
    {
        "nome": "Andrés Iniesta",
        "seguidores_instagram": 43400000,
        "descricao_rapida": "Ex-jogador de futebol espanhol",
        "pais_origem": "Espanha",
    },
    {
        "nome": "Tata Werneck",
        "seguidores_instagram": 57000000,
        "descricao_rapida": "Atriz e comediante brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Larissa Manoela",
        "seguidores_instagram": 54200000,
        "descricao_rapida": "Atriz e cantora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Maisa Silva",
        "seguidores_instagram": 48000000,
        "descricao_rapida": "Atriz e apresentadora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Bruna Marquezine",
        "seguidores_instagram": 45200000,
        "descricao_rapida": "Atriz brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Marina Ruy Barbosa",
        "seguidores_instagram": 46000000,
        "descricao_rapida": "Atriz brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Gusttavo Lima",
        "seguidores_instagram": 44600000,
        "descricao_rapida": "Cantor e compositor brasileiro",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Virginia Fonseca",
        "seguidores_instagram": 45000000,
        "descricao_rapida": "Influenciadora digital e empresária",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Carlinhos Maia",
        "seguidores_instagram": 30900000,
        "descricao_rapida": "Influenciador digital e comediante",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Luan Santana",
        "seguidores_instagram": 34800000,
        "descricao_rapida": "Cantor e compositor brasileiro",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Wesley Safadão",
        "seguidores_instagram": 39000000,
        "descricao_rapida": "Cantor e produtor musical",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Ivete Sangalo",
        "seguidores_instagram": 35400000,
        "descricao_rapida": "Cantora e compositora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Simone Mendes",
        "seguidores_instagram": 38600000,
        "descricao_rapida": "Cantora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Juliette Freire",
        "seguidores_instagram": 32400000,
        "descricao_rapida": "Cantora e influenciadora digital",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Paolla Oliveira",
        "seguidores_instagram": 36100000,
        "descricao_rapida": "Atriz brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Sabrina Sato",
        "seguidores_instagram": 31400000,
        "descricao_rapida": "Apresentadora e atriz brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Gisele Bündchen",
        "seguidores_instagram": 22500000,
        "descricao_rapida": "Supermodelo e ativista ambiental",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Eliana",
        "seguidores_instagram": 32000000,
        "descricao_rapida": "Apresentadora de televisão brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Tatá Werneck",
        "seguidores_instagram": 57000000,
        "descricao_rapida": "Atriz e humorista brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Iza",
        "seguidores_instagram": 17600000,
        "descricao_rapida": "Cantora e compositora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Ludmilla",
        "seguidores_instagram": 30400000,
        "descricao_rapida": "Cantora e compositora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Luísa Sonza",
        "seguidores_instagram": 31700000,
        "descricao_rapida": "Cantora e compositora brasileira",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Pabllo Vittar",
        "seguidores_instagram": 12800000,
        "descricao_rapida": "Drag queen e cantora",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Gloria Groove",
        "seguidores_instagram": 6300000,
        "descricao_rapida": "Drag queen e cantora",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Manu Gavassi",
        "seguidores_instagram": 15600000,
        "descricao_rapida": "Cantora, atriz e diretora",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Rafa Kalimann",
        "seguidores_instagram": 22600000,
        "descricao_rapida": "Influenciadora digital e apresentadora",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Bianca Andrade",
        "seguidores_instagram": 19900000,
        "descricao_rapida": "Empresária e influenciadora digital",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Flavia Pavanelli",
        "seguidores_instagram": 19000000,
        "descricao_rapida": "Atriz e influenciadora digital",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Jade Picon",
        "seguidores_instagram": 22100000,
        "descricao_rapida": "Influenciadora digital e atriz",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Viih Tube",
        "seguidores_instagram": 30900000,
        "descricao_rapida": "Youtuber e influenciadora digital",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Gkay",
        "seguidores_instagram": 21000000,
        "descricao_rapida": "Comediante e influenciadora digital",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Camila Coelho",
        "seguidores_instagram": 10000000,
        "descricao_rapida": "Influenciadora de moda e beleza",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Thássia Naves",
        "seguidores_instagram": 4000000,
        "descricao_rapida": "Influenciadora de moda e luxo",
        "pais_origem": "Brasil",
    },
    {
        "nome": "Chiara Ferragni",
        "seguidores_instagram": 29400000,
        "descricao_rapida": "Empreendedora de moda italiana",
        "pais_origem": "Itália",
    },
    {
        "nome": "Nikkie de Jager",
        "seguidores_instagram": 20000000,
        "descricao_rapida": "Maquiadora e youtuber holandesa",
        "pais_origem": "Holanda",
    },
    {
        "nome": "Huda Kattan",
        "seguidores_instagram": 54100000,
        "descricao_rapida": "Maquiadora e empresária iraquiana-americana",
        "pais_origem": "Iraque",
    },
    {
        "nome": "James Charles",
        "seguidores_instagram": 21800000,
        "descricao_rapida": "Maquiador e youtuber americano",
        "pais_origem": "Estados Unidos",
    },
    {
        "nome": "Lele Pons",
        "seguidores_instagram": 53800000,
        "descricao_rapida": "Celebridade da internet venezuelana-americana",
        "pais_origem": "Venezuela",
    },
    {
        "nome": "German Garmendia",
        "seguidores_instagram": 20000000,
        "descricao_rapida": "Youtuber e comediante chileno",
        "pais_origem": "Chile",
    },
    {
        "nome": "PewDiePie (Felix Kjellberg)",
        "seguidores_instagram": 21300000,
        "descricao_rapida": "Youtuber e comediante sueco",
        "pais_origem": "Suécia",
    },
    {
        "nome": "Khaby Lame",
        "seguidores_instagram": 79800000,
        "descricao_rapida": "Criador de vídeos senegalês-italiano",
        "pais_origem": "Senegal",
    },
]
